name: CI/CD Pipeline

# Триггеры для запуска workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Чекаут кода
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Настройка Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Установка docker-compose (используем готовое действие)
      - name: Install docker-compose
        uses: docker/setup-docker-compose@v1

      # 4. Логин в Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
          registry: docker.io

      # 5. Сборка и пуш Docker-образов
      - name: Build and push Docker images
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/task-service:${{ github.sha }} ./TaskService
          docker push ${{ env.DOCKERHUB_USERNAME }}/task-service:${{ github.sha }}
          docker tag ${{ env.DOCKERHUB_USERNAME }}/task-service:${{ github.sha }} ${{ env.DOCKERHUB_USERNAME }}/task-service:latest
          docker push ${{ env.DOCKERHUB_USERNAME }}/task-service:latest
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/category-service:${{ github.sha }} ./CategoryService
          docker push ${{ env.DOCKERHUB_USERNAME }}/category-service:${{ github.sha }}
          docker tag ${{ env.DOCKERHUB_USERNAME }}/category-service:${{ github.sha }} ${{ env.DOCKERHUB_USERNAME }}/category-service:latest
          docker push ${{ env.DOCKERHUB_USERNAME }}/category-service:latest

      # 6. Разворачиваем контейнеры через docker-compose
      - name: Deploy containers
        run: |
          docker-compose up -d

      # 7. Проверка работоспособности через curl
      - name: Test containers health
        run: |
          curl --retry 10 --retry-delay 5 --retry-max-time 120 http://localhost:5001/api/Tasks
          curl --retry 10 --retry-delay 5 --retry-max-time 120 http://localhost:5000/api/Categories

      # 8. Очистка после тестов
      - name: Cleanup
        if: always()
        run: |
          docker-compose down --volumes
